// components/search/Filters.vue
<template>
  <div class="filters-container">
    <!-- Active Filters Chips -->
    <div v-if="hasActiveFilters" class="active-filters-section mb-4">
      <div class="active-filters-chips">

        <!-- Card Types Chips -->
        <div v-for="cardType in selectedCardTypes || []" :key="`type-${cardType}`">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="removeCardType(cardType)">{{ cardType }}
          </UButton>
        </div>

        <!-- Colors Chips -->
        <div v-for="color in selectedColors || []" :key="`color-${color}`">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="removeColor(color)">
            <ManaIcon :type="cardColorToSymbol(color)" class="mr-1" />{{ color }}
          </UButton>
        </div>

        <!-- Rarities Chips -->
        <div v-for="rarity in selectedRarities || []" :key="`rarity-${rarity}`">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="removeRarity(rarity)">{{ rarity }}
          </UButton>
        </div>

        <!-- Stats Chips -->
        <div v-if="selectedCMC">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="clearCMC()">CMC {{ selectedCMCOption || 'Equal To' }} {{
              selectedCMC }}
          </UButton>
        </div>

        <div v-if="selectedPower">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="clearPower()">Power {{ selectedPowerOption || 'Equal To' }} {{
              selectedPower }}
          </UButton>
        </div>

        <div v-if="selectedToughness">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="clearToughness()">Toughness {{ selectedToughnessOption || 'Equal To' }} {{
              selectedToughness }}
          </UButton>
        </div>

        <!-- Color Filter Option Chip -->
        <div v-if="selectedColorFilterOption && selectedColorFilterOption !== 'Contains At Least'">
          <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
            icon="i-lucide-circle-x" @click="clearColorFilterOption()">Color: {{ selectedColorFilterOption }}
          </UButton>
        </div>

        <!-- Formats Chips -->
        <template v-for="(formatItem, index) in selectedCardFormats || []" :key="`format-${index}`">
          <div v-if="formatItem.format || formatItem.status">
            <UButton class="cursor-pointer ma-1 rounded-pill" size="sm" color="neutral" variant="outline"
              icon="i-lucide-circle-x" @click="removeFormat(index)">{{ formatItem.format || 'Any' }} - {{
                formatItem.status || 'Any Status' }}
            </UButton>
          </div>
        </template>

        <!-- Clear All Button -->
        <UButton v-if="hasActiveFilters" color="error" size="sm" class="ma-1 rounded-pill" @click="clearAllFilters"
          icon="i-lucide-circle-x">
          Clear All
        </UButton>
      </div>
    </div>
    <UCollapsible class="flex flex-col gap-2 mb-4">
      <UButton class="filters-toggle-btn mb-3" label="Filters" color="primary" variant="subtle"
        trailing-icon="i-lucide-chevron-down" :ui="{
          trailingIcon: 'group-data-[state=open]:rotate-180 transition-transform duration-200'
        }" block />

      <!-- Filters Content -->
      <template #content class="filters-content mb-4">
        <UAccordion type="multiple" :unmount-on-hide="false" :items="items">
          <!-- Types Filter -->
          <template #types>
            <div class="accordion-item">
              <USelectMenu v-model="selectedCardTypes" :items="cardTypes" placeholder="Select card types" multiple
                class="w-full" />
            </div>
          </template>
          <!-- Colors Filter -->
          <template #colors>
            <div class="accordion-item">
              <USelect v-model="selectedColorFilterOption" :items="colorFilterOptions" placeholder="Color matching"
                clearable class="w-full" />
              <div class="color-checkboxes flex flex-wrap">
                <UCheckboxGroup :items="cardColors" :orientation="orientation" variant="card" v-model="selectedColors"
                  class="w-full flex flex-wrap">
                  <template #label="{ item }">
                    <ManaIcon
                      :type="cardColorToSymbol((item as { value: 'White' | 'Blue' | 'Black' | 'Red' | 'Green' | 'Colorless' }).value)"
                      class="mr-1" />
                    <!-- Typescript gets confused with the CheckboxGroupItem type so we have to help it out a bit -->
                    {{ (item as { value: string }).value }}
                  </template>
                </UCheckboxGroup>
              </div>
            </div>
          </template>
          <!-- Rarities Filter -->
          <template #rarities>
            <div class="accordion-item flex flex-wrap">
              <UCheckboxGroup :items="cardRarities" :orientation="orientation" variant="card"
                v-model="selectedRarities" />
            </div>
          </template>
          <!-- Stats Filter -->
          <template #stats>
            <div class="accordion-item">
              <div class="stats-grid">
                <div class="stat-group">
                  <label class="stat-label">Mana Cost</label>
                  <USelect placeholder="Mana Cost Comparison" v-model="selectedCMCOption"
                    :items="comparisonOperators" />
                  <UInput v-model="selectedCMC" placeholder="Any value, e.g. '3'" type="number" />
                </div>
                <div class="stat-group">
                  <label class="stat-label">Power</label>
                  <USelect placeholder="Power Comparison" v-model="selectedPowerOption" :items="comparisonOperators" />
                  <UInput v-model="selectedPower" placeholder="Any value, e.g. '2'" type="number" />
                </div>
                <div class="stat-group">
                  <label class="stat-label">Toughness</label>
                  <USelect placeholder="Toughness Comparison" v-model="selectedToughnessOption"
                    :items="comparisonOperators" />
                  <UInput v-model="selectedToughness" placeholder="Any value, e.g. '2'" type="number" />
                </div>
              </div>
            </div>
          </template>
          <!-- Formats Filter -->
          <template #formats>
            <div class="accordion-item">
              <div v-if="selectedCardFormats && selectedCardFormats.length > 0">
                <div v-for="(format, i) in selectedCardFormats" :key="i" class="mb-3" style="display: flex; gap: 8px;">
                  <USelect class="min-w-[160px]" v-model="format.format" :items="cardFormats" label="Format"
                    clearable />
                  <USelect class="min-w-[160px]" v-model="format.status" :items="cardFormatStatuses" label="Status"
                    clearable />
                </div>
              </div>
              <UButton @click="addFormatRow" color="primary" size="sm" icon="i-lucide-plus">
                Add Format
              </UButton>
            </div>
          </template>
        </UAccordion>
      </template>
    </UCollapsible>
  </div>
</template>
<script lang="ts" setup>
import { computed } from 'vue';
import { z } from 'zod';
import { CardType, CardColor, CardRarity, CardFormat, CardFormatStatus, cardColorToSymbol } from '~/models/cardModel';
import type { CardSearchFilters } from '~/models/searchModel';
import ManaIcon from '../manaIcon.vue';
import type { AccordionItem, CheckboxGroupItem, CheckboxGroupValue } from '@nuxt/ui';

type CardColorType = z.infer<typeof CardColor>;
type CardRarityType = z.infer<typeof CardRarity>;

const screenWidth = ref(0)

onMounted(() => {
  screenWidth.value = window.innerWidth
  window.addEventListener('resize', () => {
    if (window && window.innerWidth) {
      screenWidth.value = window.innerWidth;
    }
  })
})

const orientation: Ref<'vertical' | 'horizontal'> = computed(() =>
  screenWidth.value < 768 ? 'vertical' : 'horizontal'
)

const { modelValue } = defineProps<{ modelValue?: CardSearchFilters }>();

const emit = defineEmits<{
  'update:modelValue': [value: CardSearchFilters]
}>();

const items = [
  {
    label: 'Card Types',
    icon: 'i-lucide-shapes',
    slot: 'types' as const
  },
  {
    label: 'Colors',
    icon: 'i-lucide-palette',
    slot: 'colors' as const
  },
  {
    label: 'Rarities',
    icon: 'i-lucide-star',
    slot: 'rarities' as const
  },
  {
    label: 'Stats',
    icon: 'i-lucide-calculator',
    slot: 'stats' as const
  },
  {
    label: 'Formats',
    icon: 'i-lucide-trophy',
    slot: 'formats' as const
  }
] satisfies AccordionItem[]

const cardTypes = CardType.options;
const cardFormats = CardFormat.options;
const cardFormatStatuses = CardFormatStatus.options;
const colorFilterOptions = [
  'Match Exactly',
  'Contains At Least',
  'Contains At Most',
];
const comparisonOperators = [
  'Equal To',
  'Not Equal To',
  'Greater Than',
  'Less Than',
];

function updateFilters(updates: Partial<CardSearchFilters>) {
  const current = modelValue || {} as CardSearchFilters;
  const newValue = { ...current, ...updates };
  emit('update:modelValue', newValue);
}

// Computed property to check if there are any active filters
const hasActiveFilters = computed(() => {
  const filters = modelValue;
  if (!filters) return false;

  return !!(
    (filters.selectedCardTypes && filters.selectedCardTypes.length > 0) ||
    (filters.selectedColors && filters.selectedColors.length > 0) ||
    (filters.selectedRarities && filters.selectedRarities.length > 0) ||
    filters.selectedCMC ||
    filters.selectedPower ||
    filters.selectedToughness ||
    (filters.selectedColorFilterOption && filters.selectedColorFilterOption !== 'Contains At Least') ||
    (filters.selectedCardFormats && filters.selectedCardFormats.length > 0)
  );
});

const selectedCardTypes = computed({
  get: () => modelValue?.selectedCardTypes,
  set: (value) => updateFilters({ selectedCardTypes: value })
});

const selectedColorFilterOption = computed({
  get: () => modelValue?.selectedColorFilterOption,
  set: (value) => {
    updateFilters({ selectedColorFilterOption: value })
  }
});

const cardColors = CardColor.options.map(color => ({
  label: color,
  value: color
})) as CheckboxGroupItem[];

const selectedColors = computed({
  get: () => modelValue?.selectedColors || [],
  set: (value) => updateFilters({ selectedColors: value })
});

const cardRarities = CardRarity.options.map(rarity => ({
  label: rarity,
  value: rarity
})) as CheckboxGroupItem[];

const selectedRarities = computed({
  get: () => modelValue?.selectedRarities || [],
  set: (value) => updateFilters({ selectedRarities: value })
});

const selectedCMCOption = computed({
  get: () => modelValue?.selectedCMCOption,
  set: (value) => updateFilters({ selectedCMCOption: value })
});

const selectedPowerOption = computed({
  get: () => modelValue?.selectedPowerOption,
  set: (value) => updateFilters({ selectedPowerOption: value })
});

const selectedToughnessOption = computed({
  get: () => modelValue?.selectedToughnessOption,
  set: (value) => updateFilters({ selectedToughnessOption: value })
});

const selectedCMC = computed({
  get: () => modelValue?.selectedCMC ? Number(modelValue.selectedCMC) : undefined,
  set: (value) => updateFilters({ selectedCMC: value ? String(value) : undefined })
});

const selectedPower = computed({
  get: () => modelValue?.selectedPower ? Number(modelValue.selectedPower) : undefined,
  set: (value) => updateFilters({ selectedPower: value ? String(value) : undefined })
});

const selectedToughness = computed({
  get: () => modelValue?.selectedToughness ? Number(modelValue.selectedToughness) : undefined,
  set: (value) => updateFilters({ selectedToughness: value ? String(value) : undefined })
});

const selectedCardFormats = computed({
  get: () => modelValue?.selectedCardFormats,
  set: (value) => updateFilters({ selectedCardFormats: value })
});

function addFormatRow() {
  const currentFormats = [...(modelValue?.selectedCardFormats || [])];
  currentFormats.push({ format: undefined, status: undefined });
  updateFilters({ selectedCardFormats: currentFormats });
}

// Chip removal functions
function removeCardType(cardType: string) {
  const currentTypes = [...(modelValue?.selectedCardTypes || [])];
  const index = currentTypes.indexOf(cardType as any);
  if (index !== -1) {
    currentTypes.splice(index, 1);
    updateFilters({ selectedCardTypes: currentTypes.length > 0 ? currentTypes : undefined });
  }
}

function removeColor(color: CardColorType) {
  const currentColors = [...(modelValue?.selectedColors || [])];
  const index = currentColors.indexOf(color);
  if (index !== -1) {
    currentColors.splice(index, 1);
    updateFilters({ selectedColors: currentColors.length > 0 ? currentColors : undefined });
  }
}

function removeRarity(rarity: CardRarityType) {
  const currentRarities = [...(modelValue?.selectedRarities || [])];
  const index = currentRarities.indexOf(rarity);
  if (index !== -1) {
    currentRarities.splice(index, 1);
    updateFilters({ selectedRarities: currentRarities.length > 0 ? currentRarities : undefined });
  }
}

function clearCMC() {
  updateFilters({ selectedCMC: undefined, selectedCMCOption: undefined });
}

function clearPower() {
  updateFilters({ selectedPower: undefined, selectedPowerOption: undefined });
}

function clearToughness() {
  updateFilters({ selectedToughness: undefined, selectedToughnessOption: undefined });
}

function clearColorFilterOption() {
  updateFilters({ selectedColorFilterOption: undefined });
}

function removeFormat(index: number) {
  const currentFormats = [...(modelValue?.selectedCardFormats || [])];
  currentFormats.splice(index, 1);
  updateFilters({ selectedCardFormats: currentFormats.length > 0 ? currentFormats : undefined });
}

function clearAllFilters() {
  updateFilters({
    selectedCardTypes: undefined,
    selectedColors: undefined,
    selectedRarities: undefined,
    selectedCMC: undefined,
    selectedPower: undefined,
    selectedToughness: undefined,
    selectedCMCOption: undefined,
    selectedPowerOption: undefined,
    selectedToughnessOption: undefined,
    selectedColorFilterOption: undefined,
    selectedCardFormats: undefined
  });
}
</script>

<style scoped>
.filters-container {
  width: 100%;
}

.filters-toggle-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.filters-toggle-btn .v-icon {
  transition: transform 0.3s ease-in-out;
}

.rotate-180 {
  transform: rotate(180deg);
}

.transition-transform {
  transition: transform 0.3s ease-in-out;
}

.filters-content {
  margin-top: 8px;
}

.active-filters-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  align-items: center;
}

.accordion-item {
  margin-bottom: 16px;
}

.color-checkboxes {
  margin-top: 8px;
  width: 100%;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

@media (max-width: 768px) {
  .stats-grid {
    grid-template-columns: 1fr;
  }
}

.stat-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.stat-label {
  font-size: 0.875rem;
  font-weight: 500;
  color: rgba(255, 255, 255, 0.87);
  margin-bottom: 0;
  display: block;
}
</style>

// src/components/search/Filters.tsx
"use client";

import { ChevronDownIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";

import { Button } from "@/components/catalyst/button";
import { Checkbox, CheckboxField } from "@/components/catalyst/checkbox";
import { Field, FieldGroup } from "@/components/catalyst/fieldset";
import { Input } from "@/components/catalyst/input";
import { Select } from "@/components/catalyst/select";
import { Text } from "@/components/catalyst/text";
import {
  CardFormat,
  CardFormatStatus,
  CardRarity,
  CardType,
} from "@/models/cardModel";
import {
  type CardSearchFilters,
  CardSearchFiltersSchema,
  type ColorFilterOption,
  type ComparisonOperator,
} from "@/models/searchModel";

interface FiltersProps {
  filters: CardSearchFilters;
  onFiltersChange: (filters: CardSearchFilters) => void;
  isVisible: boolean;
}

const COLORS = [
  { key: "White", className: "ms ms-w ms-cost" },
  { key: "Blue", className: "ms ms-u ms-cost" },
  { key: "Black", className: "ms ms-b ms-cost" },
  { key: "Red", className: "ms ms-r ms-cost" },
  { key: "Green", className: "ms ms-g ms-cost" },
] as const;

interface FilterSectionProps {
  title: string;
  children: React.ReactNode;
  sectionKey: string;
  expandedSections: Set<string>;
  onToggleSection: (section: string) => void;
}

const FilterSection = ({
  title,
  children,
  sectionKey,
  expandedSections,
  onToggleSection,
}: FilterSectionProps) => {
  const isExpanded = expandedSections.has(sectionKey);

  return (
    <div className="border-b border-zinc-200 dark:border-zinc-700">
      <button
        type="button"
        className="flex w-full items-center justify-between py-4 text-left"
        onClick={() => onToggleSection(sectionKey)}
      >
        <Text className="font-medium text-zinc-900 dark:text-zinc-100">
          {title}
        </Text>
        <ChevronDownIcon
          className={`h-5 w-5 text-zinc-500 transition-transform ${
            isExpanded ? "rotate-180" : ""
          }`}
        />
      </button>
      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="pb-4">{children}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export function Filters({ filters, onFiltersChange, isVisible }: FiltersProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(["colors"]),
  );

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  const updateFilters = (updates: Partial<CardSearchFilters>) => {
    onFiltersChange({ ...filters, ...updates });
  };

  const clearAllFilters = () => {
    onFiltersChange(CardSearchFiltersSchema.parse({}));
  };

  const hasActiveFilters = () => {
    return (
      filters.selectedCardTypes.length > 0 ||
      Object.values(filters.selectedColors || {}).some(Boolean) ||
      Object.values(filters.selectedRarities || {}).some(Boolean) ||
      filters.selectedCMC !== "" ||
      filters.selectedPower !== "" ||
      filters.selectedToughness !== "" ||
      filters.selectedCardFormats.length > 0
    );
  };

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ height: 0, opacity: 0 }}
          animate={{ height: "auto", opacity: 1 }}
          exit={{ height: 0, opacity: 0 }}
          transition={{ duration: 0.3 }}
          className="overflow-hidden"
        >
          <div className="px-4 py-6">
            <div className="mb-4 flex items-center justify-between">
              <Text className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">
                Advanced Filters
              </Text>
              <Button
                color="light"
                onClick={clearAllFilters}
                disabled={!hasActiveFilters()}
                className="text-sm"
              >
                <XMarkIcon data-slot="icon" />
                Clear All
              </Button>
            </div>

            <div className="space-y-0">
              {/* Card Types */}
              <FilterSection
                title="Card Types"
                sectionKey="cardTypes"
                expandedSections={expandedSections}
                onToggleSection={toggleSection}
              >
                <FieldGroup>
                  <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
                    {CardType.options.map((type) => (
                      <CheckboxField key={type}>
                        <Checkbox
                          checked={filters.selectedCardTypes.includes(type)}
                          onChange={(checked) => {
                            const newTypes = checked
                              ? [...filters.selectedCardTypes, type]
                              : filters.selectedCardTypes.filter(
                                  (t) => t !== type,
                                );
                            updateFilters({ selectedCardTypes: newTypes });
                          }}
                        />
                        <Text>{type}</Text>
                      </CheckboxField>
                    ))}
                  </div>
                </FieldGroup>
              </FilterSection>

              {/* Colors */}
              <FilterSection
                title="Colors"
                sectionKey="colors"
                expandedSections={expandedSections}
                onToggleSection={toggleSection}
              >
                <FieldGroup>
                  <div className="space-y-4">
                    <div className="flex flex-wrap gap-4 items-center">
                      {COLORS.map(({ key, className }) => (
                        <CheckboxField
                          key={key}
                          className="flex-row items-center gap-2"
                        >
                          <Checkbox
                            checked={
                              filters.selectedColors?.[
                                key as keyof typeof filters.selectedColors
                              ] || false
                            }
                            onChange={(checked) => {
                              updateFilters({
                                selectedColors: {
                                  White: false,
                                  Blue: false,
                                  Black: false,
                                  Red: false,
                                  Green: false,
                                  ...filters.selectedColors,
                                  [key]: checked,
                                },
                              });
                            }}
                          />
                          <span className={`${className} text-lg`} />
                          <Text className="font-medium">{key}</Text>
                        </CheckboxField>
                      ))}

                      {/* Colorless checkbox */}
                      <CheckboxField className="flex-row items-center gap-2">
                        <Checkbox
                          checked={false}
                          onChange={() => {
                            // Handle colorless selection if needed
                          }}
                        />
                        <span className="ms ms-c ms-cost text-lg" />
                        <Text className="font-medium">Colorless</Text>
                      </CheckboxField>
                    </div>

                    <div className="flex items-center gap-4">
                      <Select
                        value={filters.selectedColorFilterOption}
                        onChange={(e) =>
                          updateFilters({
                            selectedColorFilterOption: e.target
                              .value as ColorFilterOption,
                          })
                        }
                        className="w-48"
                      >
                        <option value="Match Exactly">
                          Exactly these colors
                        </option>
                        <option value="Contains At Least">Including</option>
                        <option value="Contains At Most">At most</option>
                      </Select>
                    </div>

                    <Text className="text-sm text-zinc-600 dark:text-zinc-400 italic">
                      "Including" means cards that are all the colors you
                      select, with or without any others. "At most" means cards
                      that have some or all of the colors you select, plus
                      colorless.
                    </Text>
                  </div>
                </FieldGroup>
              </FilterSection>

              {/* Rarity */}
              <FilterSection
                title="Rarity"
                sectionKey="rarity"
                expandedSections={expandedSections}
                onToggleSection={toggleSection}
              >
                <FieldGroup>
                  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                    {CardRarity.options.map((rarity) => (
                      <CheckboxField key={rarity}>
                        <Checkbox
                          checked={
                            filters.selectedRarities?.[
                              rarity as keyof typeof filters.selectedRarities
                            ] || false
                          }
                          onChange={(checked) => {
                            updateFilters({
                              selectedRarities: {
                                ...filters.selectedRarities,
                                [rarity]: checked,
                              },
                            });
                          }}
                        />
                        <Text>{rarity}</Text>
                      </CheckboxField>
                    ))}
                  </div>
                </FieldGroup>
              </FilterSection>

              {/* Stats */}
              <FilterSection
                title="Card Stats"
                sectionKey="stats"
                expandedSections={expandedSections}
                onToggleSection={toggleSection}
              >
                <FieldGroup>
                  <div className="grid gap-4 sm:grid-cols-3">
                    {/* CMC */}
                    <Field>
                      <Text className="mb-2 text-sm font-medium">
                        Converted Mana Cost
                      </Text>
                      <div className="space-y-2">
                        <Select
                          value={filters.selectedCMCOption}
                          onChange={(e) =>
                            updateFilters({
                              selectedCMCOption: e.target
                                .value as ComparisonOperator,
                            })
                          }
                        >
                          <option value="Equal To">Equal To</option>
                          <option value="Not Equal To">Not Equal To</option>
                          <option value="Greater Than">Greater Than</option>
                          <option value="Less Than">Less Than</option>
                        </Select>
                        <Input
                          type="number"
                          placeholder="CMC"
                          value={filters.selectedCMC}
                          onChange={(e) =>
                            updateFilters({ selectedCMC: e.target.value })
                          }
                          min="0"
                        />
                      </div>
                    </Field>

                    {/* Power */}
                    <Field>
                      <Text className="mb-2 text-sm font-medium">Power</Text>
                      <div className="space-y-2">
                        <Select
                          value={filters.selectedPowerOption}
                          onChange={(e) =>
                            updateFilters({
                              selectedPowerOption: e.target
                                .value as ComparisonOperator,
                            })
                          }
                        >
                          <option value="Equal To">Equal To</option>
                          <option value="Not Equal To">Not Equal To</option>
                          <option value="Greater Than">Greater Than</option>
                          <option value="Less Than">Less Than</option>
                        </Select>
                        <Input
                          type="number"
                          placeholder="Power"
                          value={filters.selectedPower}
                          onChange={(e) =>
                            updateFilters({ selectedPower: e.target.value })
                          }
                        />
                      </div>
                    </Field>

                    {/* Toughness */}
                    <Field>
                      <Text className="mb-2 text-sm font-medium">
                        Toughness
                      </Text>
                      <div className="space-y-2">
                        <Select
                          value={filters.selectedToughnessOption}
                          onChange={(e) =>
                            updateFilters({
                              selectedToughnessOption: e.target
                                .value as ComparisonOperator,
                            })
                          }
                        >
                          <option value="Equal To">Equal To</option>
                          <option value="Not Equal To">Not Equal To</option>
                          <option value="Greater Than">Greater Than</option>
                          <option value="Less Than">Less Than</option>
                        </Select>
                        <Input
                          type="number"
                          placeholder="Toughness"
                          value={filters.selectedToughness}
                          onChange={(e) =>
                            updateFilters({ selectedToughness: e.target.value })
                          }
                        />
                      </div>
                    </Field>
                  </div>
                </FieldGroup>
              </FilterSection>

              {/* Formats */}
              <FilterSection
                title="Format Legality"
                sectionKey="formats"
                expandedSections={expandedSections}
                onToggleSection={toggleSection}
              >
                <FieldGroup>
                  <div className="grid gap-3 sm:grid-cols-2">
                    {CardFormat.options.map((format) => {
                      const currentFilter = filters.selectedCardFormats.find(
                        (f) => f.format === format,
                      );

                      return (
                        <div
                          key={format}
                          className="flex items-center justify-between gap-3"
                        >
                          <Text className="text-sm font-medium flex-1">
                            {format}
                          </Text>
                          <Select
                            value={currentFilter?.status || ""}
                            onChange={(e) => {
                              const newFormats =
                                filters.selectedCardFormats.filter(
                                  (f) => f.format !== format,
                                );

                              if (e.target.value) {
                                newFormats.push({
                                  format,
                                  status: e.target.value,
                                });
                              }

                              updateFilters({
                                selectedCardFormats: newFormats,
                              });
                            }}
                            className="w-32"
                          >
                            <option value="">Any</option>
                            {CardFormatStatus.options.map((status) => (
                              <option key={status} value={status}>
                                {status}
                              </option>
                            ))}
                          </Select>
                        </div>
                      );
                    })}
                  </div>
                </FieldGroup>
              </FilterSection>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
